// This is generated by scripts/ASTGenerator.ts
struct BinaryExpression {
	struct Expression *left;
	struct Token *op;
	struct Expression *right;
};
struct GroupingExpression {
	struct Token *open;
	struct Expression *grouped;
	struct Token *close;
};
struct UnaryExpression {
	struct Expression *expression;
	struct Token *unary;
};
struct LiteralExpression {
	struct Token *literal;
};
struct VariableExpression {
	struct Token *variable;
};
struct AssignExpression {
	struct Token *variable;
	struct Expression *value;
};
struct ExpressionStatement {
	struct Expression *expr;
	struct Token *semicolon;
};
struct PrintStatement {
	struct Token *print;
	struct Expression *expr;
	struct Token *semicolon;
};
struct VarDeclaration {
	struct Token *var;
	struct Token *identifier;
	struct Token *equals;
	struct Expression *expr;
	struct Token *semi;
};
struct StatementDeclaration {
	struct Statement *statement;
	struct Token *identifier;
	struct Token *equals;
	struct Expression *expr;
	struct Token *semi;
};
